export const PATHS = {
  AUTH: {
    ROOT: '/auth',
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    VERIFY_EMAIL: '/auth/verify-email',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  DASHBOARD: '/dashboard',
  SCHEDULES: '/schedules',
  DESTINATIONS: '/destinations',
  TAGS: '/tags',
  LOCATION_TYPES: '/location-types',
  LOCATIONS: '/locations',
  AMENITIES: '/amenities',
  USERS: '/users',
  PROFILE: '/profile',
  PARTNER_LOCATIONS: '/partner/locations',
  CREATE_TRIP: '/create-trip',
  ITINERARY: '/itinerary',
  UNAUTHORIZED: '/403',
  NOT_FOUND: '*',
};
