export const PATHS = {
  AUTH: {
    ROOT: '/auth',
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    VERIFY_EMAIL: '/auth/verify-email',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  DASHBOARD: '/dashboard',
  SCHEDULES: '/schedules',
  DESTINATIONS: '/destinations',
  TAGS: '/tags',
  LOCATION_TYPES: '/location-types',
  LOCATIONS: '/locations',
  AMENITIES: '/amenities',
  ITINERARY: '/itinerary',
  MY_LOCATIONS: '/my-locations',
  USERS: '/users',
  USER_DETAIL: (id = ':id') => `/users/${id}`,
  REPORTED_REVIEWS: '/reviews/reported',
  LOCATION_SUBMISSIONS_REVIEW: '/admin/location-submissions',
  PROFILE: '/profile',
  PARTNER_LOCATIONS: '/partner/locations',
  CREATE_TRIP: '/create-trip',
  TRIPS_LIST: '/my-trips',
  TRIP_DETAIL: '/trips/:id',
  ACCEPT_INVITATION: '/invitations/accept',
  TRANSPORTATION: '/transportation',
  TRANSPORTATION_MANAGEMENT: '/transportation-management',
  TRANSPORT_MODES: '/transport-modes',
  TRANSIT_HUBS: '/transit-hubs',
  LOCAL_TRANSPORT_METRICS: '/local-transport-metrics',
  UNAUTHORIZED: '/403',
  NOT_FOUND: '*',
};